on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    # only trigger on main/master branches, not on tags
    branches: [main, master]

name: quarto-render
jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Obtain a copy of the repository on the runner
      - name: Check out repository
        uses: actions/checkout@v3

      # Install Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

      # Setup pandoc (might be included with Quarto action?) 
      - uses: r-lib/actions/setup-pandoc@v2
      # Setup R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Handle installing R packages from DESCRIPTION file
      - uses: r-lib/actions/setup-r-dependencies@v2
      #  with:
      #    extra-packages: any::ggplot2, local::.
      
      # Download latest version of Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          cache: 'pip'
      
      # Install jupyter via pip if it is not part of your requirements.txt
      # - name: "Install Jupyter Notebooks via Pip"
      #  run: |
      #     pip install jupyter 
      
      # Install python dependencies from requirements via pip
      - name: "Install Python dependencies via Pip"
        run: | 
           pip install -r requirements.txt

      # Render the Quarto book using GitHub actions and publish
      # We are using the built-in {{GITHUB_PAT}} environment variable.
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          #path: _book

