on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    # only trigger on main/master branches, not on tags
    branches: [main, master]

name: quarto-render
jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Download a copy of the repo
      - uses: actions/checkout@v2
      # Setup pandoc (might be included with Quarto action?) 
      - uses: r-lib/actions/setup-pandoc@v2
      # Setup R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      # Handle installing R packages from DESCRIPTION file
      #- uses: r-lib/actions/setup-r-dependencies@v2
      #  with:
      #    extra-packages: any::ggplot2, local::.
      
      # Download latest version of Python
      - uses: actions/setup-python@v2
      
      # Install python dependencies from requirements via pip
      #- name: "Install Python dependencies via Pip"
      #  run: |
      #    pip install -r requirements.txt


      # Grab a copy of quarto and render the document in all formats
      - uses: quarto-dev/quarto-actions/install-quarto@v1
      - run: |
          quarto render --to all

      # Deploy the rendered _book directory onto Pages
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _book
